### ISSUE TITLE
Error `Option::unwrap()`

### ISSUE THREAD

**Issue by theblackturtle** [nccgroup/dirble#45]
Hi, I got this error with newest source code from github

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: dirble::output::directory_name
  10: alloc::slice::<impl [T]>::sort_by::{{closure}}
  11: alloc::slice::merge_sort
  12: dirble::output::print_report
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: dirble::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
```

**Comment by sciguy16** [comment]
Hey @theblackturtle, what were the options you used that led to the panic?

**Comment by theblackturtle** [comment]
@sciguy16 This is my command
```
RUST_BACKTRACE=full ./dirble/dirble -k -B 404,429,501,502,503,403,500 -u "https://domain.com/" --scan-listable   -a "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36" -w ~/.wordlists/fast_brute.txt --scan-401 -t 100
```
This is full stack trace
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:        0x10191c7f3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hbc4a87dc97d9c209
   1:        0x101918862 - std::sys_common::backtrace::_print::h411a08c36ea9f4e9
   2:        0x10191b6f6 - std::panicking::default_hook::{{closure}}::hc6f50b761777cef2
   3:        0x10191b49f - std::panicking::default_hook::h871283332e86768d
   4:        0x10191be6f - std::panicking::rust_panic_with_hook::hddd286a9c773fc67
   5:        0x10191b99c - std::panicking::continue_panic_fmt::ha1bbafe7a6df805a
   6:        0x10191b888 - rust_begin_unwind
   7:        0x101931fc1 - core::panicking::panic_fmt::h7c36dce80bd02f4c
   8:        0x101931f06 - core::panicking::panic::h80240fd66f8680f2
   9:        0x101789da7 - dirble::output::directory_name::h83e5769dfd403f88
  10:        0x101789b42 - alloc::slice::<impl [T]>::sort_by::{{closure}}::h266f1f9c1966f934
  11:        0x101788a87 - alloc::slice::merge_sort::hda774f52cc47981f
  12:        0x1017835ee - dirble::output::print_report::hd3056d0dcab90d72
  13:        0x10177c3f5 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd370a642fa456f22
  14:        0x1017941ca - std::panicking::try::do_call::h69b4db096c860c5f
  15:        0x10191e40e - __rust_maybe_catch_panic
  16:        0x101777865 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9aa14cf42d27c531
  17:        0x10190f50d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h184cdfe19b856bb1
  18:        0x10191dd3d - std::sys::unix::thread::Thread::new::thread_start::he418bbb505b1b1b9
  19:     0x7fff7216c2ea - _pthread_body
  20:     0x7fff7216f248 - _pthread_start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0:        0x10191c7f3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hbc4a87dc97d9c209
   1:        0x101918862 - std::sys_common::backtrace::_print::h411a08c36ea9f4e9
   2:        0x10191b6f6 - std::panicking::default_hook::{{closure}}::hc6f50b761777cef2
   3:        0x10191b49f - std::panicking::default_hook::h871283332e86768d
   4:        0x10191be6f - std::panicking::rust_panic_with_hook::hddd286a9c773fc67
   5:        0x10191b99c - std::panicking::continue_panic_fmt::ha1bbafe7a6df805a
   6:        0x10191b888 - rust_begin_unwind
   7:        0x101931fc1 - core::panicking::panic_fmt::h7c36dce80bd02f4c
   8:        0x1017752c9 - core::result::unwrap_failed::h697fea3fcfe1be9b
   9:        0x1017ab4a4 - dirble::main::hc248424c2e6cb498
  10:        0x10177cee5 - std::rt::lang_start::{{closure}}::h29051f526c700680
  11:        0x10191b807 - std::panicking::try::do_call::h8037d9f03e27d896
  12:        0x10191e40e - __rust_maybe_catch_panic
  13:        0x10191c2ed - std::rt::lang_start_internal::hc8e69e673740d4ae
  14:        0x1017ac298 - main
```

**Comment by Hwatwasthat** [comment]
Looks to be here maybe (line 186, directory_output in output.rs):
```
if response.is_directory {
        if url.ends_with('/') {
            String::from(&url[0..url.len() - 1])
        } else {
            String::from(url)
        }
    } else {
        let last_slash = url.rfind('/').unwrap();
        String::from(&url[0..last_slash])
    }
```

Unwrapping the result of url.rfind looks the most likely failure point.
